doctrine:
    dbal:
        url: 'postgresql://%env(resolve:DB_USER)%:%env(resolve:DB_PASSWORD)%@db:5432/%env(resolve:DB_NAME)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
