parameters:
    app.domain: '%env(string:APP_DOMAIN)%'
    mailer.use: '%env(bool:CONFIRM_EMAIL)%'
    mailer.host: '%env(string:MAILER_HOST)%'
    mailer.user: '%env(string:MAILER_USER)%'
    mailer.password: '%env(string:MAILER_PASSWORD)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Service\Mailer:
        arguments:
            $senderEmail: '%mailer.user%'

    App\Service\Security\SecurityService:
        arguments:
            $domain: '%app.domain%'
            $useEmailConfirm: '%mailer.use%'

    App\Service\Security\MainAuthenticator:
        arguments:
            $useEmailConfirm: '%mailer.use%'

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
